### ISSUE TITLE
Bug：ascii2d访问失败

### ISSUE THREAD

**Issue by medicago087** [koishijs/koishi-plugin-image-search#10]
![image](https://user-images.githubusercontent.com/68104673/207318165-42814df4-94ed-49fb-a32c-f4a9058d5e9d.png)
![image](https://user-images.githubusercontent.com/68104673/207318265-7aed19c4-9cb8-47a2-b81d-3c2424f3f651.png)

**Comment by cpuopt** [comment]
可能是机场节点的问题，建议相同节点在浏览器试试能不能搜图

**Comment by fatinghenji** [comment]
```
2023-11-11 23:33:08 [W] search [error] ascii2d color AxiosError: Request failed with status code 403
2023-11-11 23:33:08 [W] search AxiosError: Request failed with status code 403
                            at settle (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:1967:12)
                            at BrotliDecompress.handleStreamEnd (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\axios\dist\node\axios.cjs:3062:11)
                            at BrotliDecompress.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-11-11 23:33:08 [W] search AxiosError: Request failed with status code 403
                            at request (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\lib\index.js:153:21)
                            at http (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\lib\index.js:172:30)
                            at _Quester.post (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\lib\index.js:220:16)
                            at default_1 (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-image-search\lib\ascii2d.js:17:38)
                            at runMicrotasks (<anonymous>)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async searchUrl (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-image-search\lib\index.js:51:28)
                            at async Array.<anonymous> (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1331:14)
                            at async _Command.execute (C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:1346:22)
                            at async C:\Users\VantHoff\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2174:22
 ```
403错误，尝试了更换节点，问题依旧存在
