### ISSUE TITLE
ascii2d 403ERROR

### ISSUE THREAD

**Issue by Gradua11y** [koishijs/koishi-plugin-image-search#18]
使用ascii2d搜索显示访问失败，日志如下
LOG:
2023-03-20 15:44:24 [D] message [私聊]  : ascii2d
2023-03-20 15:44:29 [D] message [私聊]  : [图片]
2023-03-20 15:44:29 [W] search [error] ascii2d color AxiosError: Request failed with status code 403
2023-03-20 15:44:29 [W] search AxiosError: Request failed with status code 403
                            at settle (C:\Users\SERVER-NAS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\node_modules\axios\dist\node\axios.cjs:1268:12)
                            at BrotliDecompress.handleStreamEnd (C:\Users\SERVER-NAS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\node_modules\axios\dist\node\axios.cjs:2446:11)
                            at BrotliDecompress.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Gradua11y** [comment]
已测试过使用相同节点正常访问ascii2d.net

**Comment by shigma** [comment]
请问配置 proxyAgent 了吗？

**Comment by Gradua11y** [comment]
经测试，全局设置挂代理照样会显示403，代理客户端日志是已经将ascii2d.net经过代理节点了，错误依旧
2023-03-20 23:03:58 [W] search [error] ascii2d color AxiosError: Request failed with status code 403
2023-03-20 23:03:58 [W] search AxiosError: Request failed with status code 403
                            at settle (C:\Users\SERVER-NAS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\node_modules\axios\dist\node\axios.cjs:1268:12)
                            at BrotliDecompress.handleStreamEnd (C:\Users\SERVER-NAS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\cordis-axios\node_modules\axios\dist\node\axios.cjs:2446:11)
                            at BrotliDecompress.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1358:12)
                            at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by copurxia** [comment]
我这边是500
``` bash
2023-07-16 22:24:01 [W] search [error] ascii2d color AxiosError: Request failed with status code 500
2023-07-16 22:24:01 [W] search AxiosError: Request failed with status code 500
                            at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
                            at IncomingMessage.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1359:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by shigma** [comment]
> 我这边是500
> 
> ```shell
> 2023-07-16 22:24:01 [W] search [error] ascii2d color AxiosError: Request failed with status code 500
> 2023-07-16 22:24:01 [W] search AxiosError: Request failed with status code 500
>                             at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
>                             at IncomingMessage.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
>                             at IncomingMessage.emit (node:events:525:35)
>                             at endReadableNT (node:internal/streams/readable:1359:12)
>                             at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> ```

你设置代理了吗？

> 可以在插件中单独添加代理设置么

可以，我晚点去加一个配置项。

**Comment by copurxia** [comment]
> > 我这边是500
> > ```shell
> > 2023-07-16 22:24:01 [W] search [error] ascii2d color AxiosError: Request failed with status code 500
> > 2023-07-16 22:24:01 [W] search AxiosError: Request failed with status code 500
> >                             at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
> >                             at IncomingMessage.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
> >                             at IncomingMessage.emit (node:events:525:35)
> >                             at endReadableNT (node:internal/streams/readable:1359:12)
> >                             at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> > ```
> 
> 你设置代理了吗？
> 
> > 可以在插件中单独添加代理设置么
> 
> 可以，我晚点去加一个配置项。

设置了，且saucenao是可用的
iqdb.org ascii2d.net saucenao.com均已设置走代理，但即使是开全局模式也只有saucenao正常工作

**Comment by copurxia** [comment]
哦它自己好了（虽然没搞懂为什么不能用

**Comment by shigma** [comment]
> 哦它自己好了（虽然没搞懂为什么不能用

我只能解释为网络问题了……
