### ISSUE TITLE
onebot适配器接入QQ，返回搜索结果时消息发送失败

### ISSUE THREAD

**Issue by YuzuharaYuka** [koishijs/koishi-plugin-image-search#35]
![567c3a0d-e19f-4e21-8ff9-846d517ef368](https://github.com/user-attachments/assets/f5f6e706-0ef1-44ae-b940-1344c64a5db9)
![455d9317206af6f0490b5bb36e24e937](https://github.com/user-attachments/assets/044dcf87-6bdd-4ed7-a56b-97ea3abf811d)
在沙盒中是正常的
![image](https://github.com/user-attachments/assets/20265865-0b3e-480d-849d-2f0c4e80db73)

**Comment by shigma** [comment]
用的哪个 onebot 服务？

**Comment by YuzuharaYuka** [comment]
> 用的哪个 onebot 服务？

LLOneBot

**Comment by idranme** [comment]
如果这些图片链接被墙，那么消息发送失败可能因为 QQ 没走代理

**Comment by YuzuharaYuka** [comment]
> 如果这些图片链接被墙，那么消息发送失败可能因为 QQ 没走代理

**Comment by KiriSuoh** [comment]
我也是同样的错误，报1200，我的实现端napcat终端以及koishi的proxy-agent都设置了代理，仍然报这个错，沙盒中无问题。

```
 Error: Error with request send_private_msg, args: {"user_id":1925477085,"message":[{"type":"text","data":{"text":"ascii2d 特征检索\n「玉体横陈-知更鸟」/「chosen鲷 二号机」"}},{"type":"image","data":{"file":"https://ascii2d.net/thumbnail/b/0/a/c/b0ac479daf2de9c973b9aefb8c6d53c3.jpg","cache":0}},{"type":"text","data":{"text":"链接：https://www.pixiv.net/artworks/125594069\n作者：https://www.pixiv.net/users/102907778"}}]}, retcode: 1200
                            at _Internal._get (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:119:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.&lt;computed&gt; [as sendPrivateMsg] (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:162:20)
                            at async OneBotMessageEncoder.flush (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:763:227)
                            at async OneBotMessageEncoder.send (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:693:5)
                            at async Proxy.sendMessage (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:423:22)
                            at async Promise.all (index 1)
                            at async default_1 (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-image-search\lib\ascii2d.js:30:9)
                            at async searchUrl (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\koishi-plugin-image-search\lib\index.js:61:28)
                            at async next (J:\koishi-desktop-win-x64-v1.1.3\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:829:16)
```

**Comment by MaikoTan** [comment]
@KiriSuoh 

> Is it now still reproducible?

它现在依旧可复现吗？
